CM-985 *FUNDING_REQUEST_ACCEPTED* event's emails
daostack/common-backend pull request #1010
Opened 2022-01-10 17:55 UTC by SobolevYuri

2022-01-12 18:08 UTC, ariel-dao commented on functions/src/notification/email/templates/proposerFundingRequestAcceptedZeroAmount.ts
> +export const proposerFundingRequestAcceptedZeroAmount = {
funding request can't be zero amount, I think it's safe to remove

2022-01-12 18:09 UTC, ariel-dao commented on functions/src/notification/email/templates/commonOwnerFundingRequestAcceptedUnknown.ts
> +commonOwnerFundingRequestAcceptedUnknown moked-up email body
what is the difference between foreign and unknown? can we remove unknown and just use foreign ?

2022-01-12 18:10 UTC, ariel-dao requested changes
added comments

2022-01-13 09:05 UTC, SobolevYuri commented on functions/src/notification/email/templates/commonOwnerFundingRequestAcceptedUnknown.ts
> +commonOwnerFundingRequestAcceptedUnknown moked-up email body
I think we can, and if it'll be needed we'll add this back then. But maybe the foreign (english) version would be enough for us.

2022-01-13 09:14 UTC, SobolevYuri reviewed
resolved

2022-01-13 09:42 UTC, ariel-dao approved these changes

2022-01-13 09:42 UTC, merged