new end point to deactivate a common
daostack/common-backend pull request #1129
Opened 2022-02-13 08:05 UTC by noamso1

2022-02-13 08:06 UTC, noamso1 commented
you can test this new endpoint like this:
curl -H 'authorization: {"uid":"DsFp7lzLWqcsoygIWnZs"}' http://localhost:5003/common-dev-dea4e/us-central1/commons/deactivate -d 'commonId=2bxGi5yAUJeQG4Aqivii'

2022-02-13 14:30 UTC, ariel-dao commented
@noamso1 looks good, have you tested it?
and can you please add it to postman?

2022-02-14 07:53 UTC, noamso1 commented
Yes. I tested it.
I don't have access to the postman team, can you send it to me?
btw I've added a curl payload example to the code at
functions/src/common/business/deactivateCommon.ts
line 15

2022-02-14 10:47 UTC, SobolevYuri requested changes
check the comments, pls

2022-02-14 10:47 UTC, SobolevYuri commented on functions/src/common/index.ts
> +    async () => {
why don't you verify the req.body by a schema?

2022-02-14 10:47 UTC, SobolevYuri commented on functions/src/common/business/deactivateCommon.ts
> +  let updatedCommon = await commonDb.update(
const

2022-02-14 11:59 UTC, noamso1 commented
@SobolevYuri  I did all your recommendations! please check.

2022-02-14 12:17 UTC, SobolevYuri approved these changes
great! thanks =)

2022-02-14 12:35 UTC, merged