CM-1297 check old pending sellers
daostack/common-backend pull request #1304
Opened 2022-04-26 11:04 UTC by noamso1

2022-05-17 10:32 UTC, noamso1 commented
@ariel-dao Everything is done. still we need to create an email template for PAYME_SELLER_VALIDATION_WARNING

2022-05-17 10:55 UTC, ariel-dao commented on functions/src/discussionMessage/triggers.ts
> +      const common: ICommon = await commonsDb.get( commonId )
update only fields you need not all the entity

2022-05-17 10:55 UTC, ariel-dao commented on functions/src/discussionMessage/triggers.ts
>      let x : number = discussion.messageCount; if ( !x ) x = 0
move `if` line

2022-05-17 10:55 UTC, ariel-dao commented on functions/src/discussionMessage/triggers.ts
>        let x : number = common.messageCount; if ( !x ) x = 0
move `if` line

2022-05-17 10:56 UTC, ariel-dao commented on functions/src/payments/business/payme/payOut/createSeller.ts
>      await sellerDb.update(seller, userId);
update only selected fields not the entire entity

2022-05-17 10:58 UTC, ariel-dao commented on functions/src/payments/business/payme/payOut/uploadSellerFiles.ts
> +    if ( !seller.userId ) return
throw errors

2022-05-17 10:58 UTC, ariel-dao commented on functions/src/payments/business/payme/payOut/uploadSellerFiles.ts
> +    if ( !seller.paymeSellerId ) return
throw errors

2022-05-17 10:59 UTC, ariel-dao commented on functions/src/payments/business/payme/payOut/uploadSellerFiles.ts
>      if (identificationDocs.length === 0) throw new NotImplementedError('The user has not any legal docs.');
might want to add a log here (payout logs)

2022-05-17 10:59 UTC, ariel-dao commented on functions/src/payments/controllers/bankAccountDetails/updateBankAccountDetails.ts
>                  const seller = await sellerDb.get(userId);
what if seller is not found? maybe user the get "throws" to throw error?

2022-05-17 11:00 UTC, ariel-dao commented on functions/src/payments/crons/checkPendingSellerStatus.ts
> +    const sellers = await sellerDb.getMany( { status: 'pending' } )
enum

2022-05-17 11:01 UTC, ariel-dao commented on functions/src/payments/crons/checkPendingSellerStatus.ts
> +                    bankAccountDetails: { userId }
why save only userId on details and not empty object?

2022-05-17 11:02 UTC, ariel-dao commented on functions/src/payments/crons/checkPendingSellerStatus.ts
> +                // clear bankAccount identification docs
should clear all of the bank account details nor just id docs

2022-05-17 11:02 UTC, ariel-dao commented on functions/src/payments/db/sellers/getSeller.ts
> +    if (!seller) {
remove, if seller doesnt exist it will return null anyway

2022-05-17 11:03 UTC, ariel-dao commented on functions/src/payments/db/sellers/getSellers.ts
> +  if (options.status) {
remove this if, you are already checking this.

also move `let` to const

2022-05-17 11:04 UTC, ariel-dao commented on functions/src/payments/db/sellers/getSellers.ts
> +    let sellers : ISeller[] = (await sellersQuery.get() as QuerySnapshot<ISeller>).docs.map(x => x.data());
I don't think you need to cast to `QuerySnapshot<ISeller>`, it should be inferred from the seller collection query.

2022-05-17 11:04 UTC, ariel-dao commented on functions/src/payments/db/sellers/getSellers.ts
> +    let sellers : ISeller[] = (await sellersQuery.get() as QuerySnapshot<ISeller>).docs.map(x => x.data());
also please avoid using names like "x" and write "seller" or doc instead

2022-05-17 11:05 UTC, ariel-dao commented on functions/src/payments/db/sellers/getSellers.ts
> +    if ( throwErr ) throw new CommonError('Could not get Sellers', e);
else, log?

2022-05-17 11:07 UTC, ariel-dao commented on functions/src/payments/db/sellers/updateSeller.ts
> +const sortKeys = ( o : object ) => // returns new recursively sorted keys object
if you really want this function, it should be in the general util folder, not here

2022-05-17 11:08 UTC, ariel-dao commented on functions/src/payments/db/sellers/updateSeller.ts
> +    if ( sellerBefore.bankAccountDetails?.identificationDocs) docsSnapBefore = JSON.stringify( sortKeys( sellerBefore.bankAccountDetails.identificationDocs ) )
you should move this entire functionality of equivalence to a util function and not run here as JSON.stringify

2022-05-17 11:08 UTC, ariel-dao commented on functions/src/payments/index.ts
> +// curl http://localhost:5003/common-dev-dea4e/us-central1/payments/test  -H 'Content-Type:application/json' -H 'authorization: {"uid":"user"}' -d '{}'
remove curl... add to postman.

2022-05-17 11:08 UTC, ariel-dao commented on functions/src/payments/index.ts
> +payments.post('/test', checkPendingSellerStatus)
???

2022-05-17 11:09 UTC, ariel-dao commented on functions/src/proposals/services/create/createFunding.ts
> +    if ( seller && seller.status == SELLER_STATUSES.REJECTED ) {
change to seller?.status == SELLER_STATUSES.REJECTED

2022-05-17 11:11 UTC, ariel-dao requested changes
change please

2022-05-17 12:38 UTC, noamso1 commented on functions/src/payments/crons/checkPendingSellerStatus.ts
> +                    bankAccountDetails: { userId }
typescript does not allow this is a required field.

2022-05-17 12:42 UTC, noamso1 commented on functions/src/payments/db/sellers/getSeller.ts
> +    if (!seller) {
it did not return null and this caused the bug. should specifically return undefined.

2022-05-17 12:43 UTC, noamso1 commented on functions/src/payments/db/sellers/getSellers.ts
> +  if (options.status) {
i don't understand, and it's not a const.

2022-05-17 12:45 UTC, noamso1 commented on functions/src/payments/db/sellers/getSellers.ts
> +    let sellers : ISeller[] = (await sellersQuery.get() as QuerySnapshot<ISeller>).docs.map(x => x.data());
changed x to "seller" in the map function. about the type - it is not inferred here because we are talking directly to the DB and not using a typed function.

2022-05-17 13:11 UTC, noamso1 commented on functions/src/payments/business/payme/payOut/uploadSellerFiles.ts
>      if (identificationDocs.length === 0) throw new NotImplementedError('The user has not any legal docs.');
payout log is per proposal and this func is for seller. we must have a proposal ID for it.

2022-05-18 07:32 UTC, ariel-dao approved these changes

2022-05-18 07:32 UTC, ariel-dao approved these changes

2022-05-18 08:01 UTC, ariel-dao approved these changes

2022-05-18 08:01 UTC, merged