added cron to calculate common score
daostack/common-backend pull request #1317
Opened 2022-05-08 12:34 UTC by noamso1

2022-05-08 12:40 UTC, noamso1 commented
@ariel-dao do we also need to
1. Create an end-point for fetching the commons sorted by score
2. Extend an existing end-point for fetching the commons, that will sort by score
3. Do nothing - FE will just fetch directly from db and will ask to sort by score

2022-05-08 12:56 UTC, ariel-dao commented
@noamso1 the 3rd option

2022-05-08 15:16 UTC, noamso1 commented
@ariel-dao so please approve and merge ...

2022-05-08 16:37 UTC, ariel-dao commented on functions/src/crons/commonScores.ts
> +    let commons = await commonsDb.getMany( {active: true })
const

2022-05-08 16:38 UTC, ariel-dao requested changes
change please

2022-05-09 07:31 UTC, ariel-dao approved these changes

2022-05-09 07:31 UTC, merged