E2E  tests
daostack/common-backend pull request #1628
Opened 2023-02-02 14:57 UTC by pepoospina

- Added a E2E test infrastructure using `mocha` and `firebase-functions-test`.
- Moved all firebase-related scripts outside of `functions` folder into it's own package.json folder in the root.
- added `docker-compose.yml` to make it simpler to run redis.
- Added `emulate` and `up` scripts to emulate firestore and run redis.
- Added `test-e2e` script to run the e2e tests. The scripts clear the firestore at every launch.
- Renamed `test` script to `test-unit`

2023-02-03 12:53 UTC, ariel-dao commented on functions/src/__e2e_tests__/commons.test.ts
> +  it("create", async () => {
might as well extend the test on full payloads

2023-02-03 12:54 UTC, ariel-dao commented on functions/src/__e2e_tests__/discussion.test.ts
> +        // expect(discussion.message).toBe(DISCUSSION_UPDATED_SUCCESS);
remove

2023-02-03 12:56 UTC, ariel-dao commented on functions/src/__e2e_tests__/discussion.test.ts
> +      before(async () => {
Let's try to restructure our tests in AAA convention, arrange, act and assert

Using before to act and checking specific results on `it` seems a little mixed, for example:

```
describe("discussion", () => { 
 it('should edit discussion', () => {
  ...
 }
)
})
```

2023-02-03 12:58 UTC, ariel-dao requested changes
I want to check in further on my local env, but it looks nice overall, look comments please

2023-02-03 13:17 UTC, pepoospina commented on functions/src/__e2e_tests__/discussion.test.ts
> +        // expect(discussion.message).toBe(DISCUSSION_UPDATED_SUCCESS);
It should be possible to do this check, but it cannot be done. This is because the request `message` property is overwritten with the `message` attribute of the discussion lost. I can remove it for now.

I left it as a reminder that, probably, the API should have a different standard for response objects where a new property `data` is distinct from `message`.

2023-02-03 13:18 UTC, pepoospina commented on functions/src/__e2e_tests__/commons.test.ts
> +  it("create", async () => {
Yes. It can. I will add it

2023-02-03 13:22 UTC, pepoospina commented on functions/src/__e2e_tests__/discussion.test.ts
> +      before(async () => {
This one is pretty common too, I think. The reason is that you can test different things on one action. 

You put the action in the `before`, and then add more than one `it`, each for different kind of things that you would expect after the action.

But yes, I can put everything inside one `it`, and if we need two `it`s I will split the common logic into a `before` then.

2023-02-06 09:39 UTC, pepoospina commented on functions/src/__e2e_tests__/discussion.test.ts
> +      before(async () => {
The other thing that this allows is to nest multiple `describe` (you cannot nest a `describe` inside an `it`). I really like this because this way you can organize the tests as "trees" of conditions, not just sequences. [This is](https://github.com/mirror-xyz/splits/blob/main/test/main.test.ts) an example of a very experienced team using this pattern.

If you don't mind I'd prefer to organize the tests I write this way.

2023-02-06 09:42 UTC, pepoospina commented on functions/src/__e2e_tests__/discussion.test.ts
> +        // expect(discussion.message).toBe(DISCUSSION_UPDATED_SUCCESS);
[This is the thing](https://github.com/daostack/common-backend/blob/fbe037cd26112cbd463a8a8712b0990d12fd5257/functions/src/util/responseExecutor.ts#L33) I'm talking about. The actual success message is lost forever.

2023-02-20 08:21 UTC, pepoospina commented on functions/src/__e2e_tests__/commons.test.ts
> +  it("create", async () => {
I prefer not to add this. Just add the things that are really needed for now. If we really want to increase the coverage, then we would need much more tests.

For example, testing the common create process requires to test all the possible combinations of parameters and protections that the code currently have. 

Adding some checks on a few more properties here would not provide great new insights.

2023-02-27 16:29 UTC, pepoospina commented
Replaced with https://github.com/daostack/common-backend/pull/1669

2023-02-27 16:29 UTC, closed without merging