Update governance endpoint
daostack/common-backend pull request #1635
Opened 2023-02-06 13:16 UTC by danielr18

2023-02-17 18:25 UTC, ariel-dao commented
This looks like the correct way to approach it, you'll need to iterate over the common members (subcollection in common) and update their circle ids accordingly if needed

2023-02-20 10:26 UTC, danielr18 commented
@ariel-dao Can you review it again?
I modified the endpoint to preserve ids

2023-02-21 12:55 UTC, ariel-dao commented on functions/src/governance/controllers/update.ts
> +            if (!isAdmin) throw new CommonError('User without `admin` role tried to update governance', req);
You can just throw Unauthorized, no need to share info like that (you can log it using logger.error)

2023-02-21 12:56 UTC, ariel-dao commented on functions/src/governance/services/update.ts
> +    // @ts-expect-error - there is an issue with the recursive partial type
We need to fix this error, can you debug it?

2023-02-21 12:56 UTC, ariel-dao commented on functions/src/governance/db/update.ts
> +        // @ts-expect-error - there is an issue with the recursive partial type
Need to fix this error

2023-02-21 12:57 UTC, ariel-dao commented on functions/src/governance/db/update.ts
> +        await GovernanceCollection.doc(governanceId).set(governanceDoc as Governance, { merge: true });
I'm not sure you want to use merge true for this type of update - what if something is deleted?

2023-02-21 12:58 UTC, ariel-dao commented on functions/src/governance/business/governanceValidationAndFormat.ts
> +import { v4 } from 'uuid';
I understand the renaming, but it really makes it hard to spot the differences if there are any - just fyi (maybe changing the name back just for this PR would make it better)

2023-02-21 13:03 UTC, ariel-dao requested changes
Looks like the right direction, we need to update the circle Ids array accordingly in case circles are being changed (check `CommonMember`). 

Also we need to recalculate proposal votes and change the weights on **live** proposals, See `onRecalculateTotalVotingPower` and `assignCircleToMemberAction`, the process is already defined so you don't need to deal with the complexity. You'd probably need to emit an event that would get caught by `onRecalculateTotalVotingPower`.

Another thing, please keep the branch updated with the base branch.

2023-02-22 02:04 UTC, danielr18 commented on functions/src/governance/db/update.ts
> +        await GovernanceCollection.doc(governanceId).set(governanceDoc as Governance, { merge: true });
Merge true was the method used before this PR, that's why I kept it as the default method, and use the `update` method in the new controller.

Do you think we should only keep update?

2023-02-22 18:25 UTC, ariel-dao commented on functions/src/governance/db/update.ts
> +        await GovernanceCollection.doc(governanceId).set(governanceDoc as Governance, { merge: true });
I think we should have another update function that won't merge, just duplicate the update and remove the merge for simple solution

2023-03-09 09:27 UTC, danielr18 commented on functions/src/governance/services/update.ts
> +    // @ts-expect-error - there is an issue with the recursive partial type
Fixed

2023-03-09 09:27 UTC, danielr18 commented on functions/src/governance/db/update.ts
> +        await GovernanceCollection.doc(governanceId).set(governanceDoc as Governance, { merge: true });
I've created another update function

2023-03-09 09:28 UTC, danielr18 commented on functions/src/governance/db/update.ts
> +        // @ts-expect-error - there is an issue with the recursive partial type
Fixed

2023-03-09 09:37 UTC, danielr18 commented
> Looks like the right direction, we need to update the circle Ids array accordingly in case circles are being changed (check `CommonMember`).

The Ids stay the same, so the CommonMember circleIds may not need to be updated.

> Also we need to recalculate proposal votes and change the weights on **live** proposals, See `onRecalculateTotalVotingPower` and `assignCircleToMemberAction`, the process is already defined so you don't need to deal with the complexity. You'd probably need to emit an event that would get caught by `onRecalculateTotalVotingPower`.
> 
> Another thing, please keep the branch updated with the base branch.

I've created a new event to trigger this function.

2023-03-09 10:58 UTC, ariel-dao approved these changes

2023-03-09 10:58 UTC, merged