Create and pin general discussion for commons
daostack/common-backend pull request #1698
Opened 2023-03-15 10:48 UTC by danielr18

Closes #1683 
Closes #1701

2023-03-15 15:40 UTC, ariel-dao commented on functions/src/users/services/create.ts
> +    return userDb.add(payload);
I think this is here by accident, make sure to work on updated branch

2023-03-15 15:40 UTC, ariel-dao requested changes
Looks good, just one fix

2023-03-16 10:49 UTC, danielr18 commented on functions/src/users/services/create.ts
> +    return userDb.add(payload);
Rebased and skipped commit

2023-03-16 11:09 UTC, ariel-dao approved these changes

2023-03-16 11:09 UTC, merged