CM-1513-permissions for users
daostack/common-backend pull request #18
Opened 2021-02-03 09:39 UTC by watchtower314

2021-02-03 11:50 UTC, watchtower314 commented on packages/firebase/functions/src/permissions/triggers/onCommonCreated.ts
> +    if (event.type === EVENT_TYPES.COMMON_CREATED) {
@alexander2001i 10x!!!! It worked!

2021-02-03 11:51 UTC, alexander2001i commented on packages/firebase/functions/src/permissions/triggers/onCommonCreated.ts
> +    if (event.type === EVENT_TYPES.COMMON_CREATED) {
👾👾👾

2021-02-04 07:02 UTC, alexander2001i requested changes

2021-02-04 07:02 UTC, alexander2001i commented on packages/firebase/functions/src/permissions/business/addPermission.ts
> + * @return               [description]
Descriptive 😅

2021-02-04 07:02 UTC, alexander2001i commented on packages/firebase/functions/src/permissions/types.ts
> +export type Role = 'founder'| 'moderator' | 'other';
@common/types

2021-02-04 11:16 UTC, watchtower314 commented on packages/firebase/functions/src/permissions/business/addPermission.ts
> + * @return               [description]
😂

2021-02-04 13:15 UTC, watchtower314 commented
@alexander2001i not quite sure what to do with these 3 eslint errors :)

2021-02-04 13:32 UTC, alexander2001i commented
@watchtower314 I fixed the two import related issues, but am not sure why it does not allow the `I`. The lint returns success locally. In any case can you please move the user types to the types package?

2021-02-10 10:33 UTC, watchtower314 commented on packages/firebase/functions/src/util/tests/helpers/mockers/getUser.mocker.ts
> +/*global firestore jest*/
![Screen Shot 2021-02-10 at 5 29 09](https://user-images.githubusercontent.com/30501647/107498200-7393d500-6b61-11eb-8eb9-79d728755af0.png)

2021-02-15 12:50 UTC, alexander2001i approved these changes

2021-02-15 12:50 UTC, alexander2001i commented on packages/firebase/functions/src/notification/notification.ts
> +const getNameString = (userData): string => {
Nice! Not also type `userData`

2021-02-15 12:51 UTC, merged