1815 inbox redo
daostack/common-backend pull request #1831
Opened 2023-05-16 18:08 UTC by ariel-dao

2023-05-16 21:19 UTC, danielr18 requested changes

2023-05-16 21:19 UTC, danielr18 commented on functions/src/commons/business/incrementFeedObjectCountForUser.ts
> +        }
This needs to be in the `onCommonFeedUpdated` trigger

2023-05-16 21:19 UTC, danielr18 commented on functions/src/chat/services/createChatChannel.ts
> +    })
Should this be added for every participant instead of just the channel creator?

2023-05-16 21:19 UTC, danielr18 commented on functions/src/commons/business/incrementFeedObjectCountForUser.ts
> +                }
This seems to be a duplicate of the above

2023-05-16 21:19 UTC, danielr18 commented on functions/src/commons/business/incrementFeedObjectCountForUser.ts
> +
This seems to be a duplicate of the above

2023-05-16 21:19 UTC, danielr18 commented on functions/src/commons/services/markFeedObjectSeenForUser.ts
> +        }
If we are not updating the feed object updatedAt, we probably should not update the inbox item updatedAt.

2023-05-16 21:19 UTC, danielr18 commented on functions/src/commons/triggers/onCommonMemberAdded.ts
> +                        updatedAt: follow.updatedAt
We may want to use `feedItem.updatedAt`.

2023-05-16 21:19 UTC, danielr18 commented on functions/src/commons/triggers/onCommonMemberAdded.ts
> +                        updatedAt: follow.updatedAt
The fix for the inbox sorting issues was to ensure that follows and feed items updatedAt matched.

2023-05-16 21:19 UTC, danielr18 commented on functions/src/commons/triggers/onNewFeedItemCreated.ts
> +import { inboxItemDb } from 'src/users/db/inbox';
Use relative path

2023-05-16 21:19 UTC, danielr18 commented on functions/src/commons/triggers/onNewFeedItemCreated.ts
> +                    updatedAt: follow.updatedAt
Should probably use feedItem.updatedAt

2023-05-16 21:19 UTC, danielr18 commented on functions/src/discussion/business/discussionMessage/setFollowForMentionedUsers.ts
> +                    updatedAt: follow.updatedAt
Should probably use feedItem.updatedAt

2023-05-16 21:19 UTC, danielr18 commented on functions/src/discussion/triggers/onDiscussionUpdated.ts
> +                        updatedAt: follow.updatedAt
Should probably use feedItem.updatedAt

2023-05-16 21:19 UTC, danielr18 commented on functions/src/proposals/business/proposals/setFollowForEligableVoters.ts
> +                    updatedAt: follow.updatedAt
Should probably use feedItem.updatedAt

2023-05-16 21:19 UTC, danielr18 commented on functions/src/users/services/followFeedItem.ts
> +            }
Why do we need this for existing follows?

2023-05-16 21:19 UTC, danielr18 commented on functions/src/users/db/inbox/add.ts
> +};
We may want to automatically skip the creation if the user already has the `(itemId,type)` pair, as we do for follows. We had some issues with duplicate items in the inbox before that was added

2023-05-16 21:19 UTC, danielr18 commented on functions/src/users/services/getInbox.ts
>              const common = await commonsDb.get(feedItemFollow.commonId, true)
chatChannels and feedItemFollows should both be awaited with Promise.all first before creating the inboxWithMetadata object, or you can create the promises before creating the object, and then await the promises in each property

This is an example showing how they are run sequentially instead of parallel

![image](https://github.com/daostack/common-backend/assets/9046616/af543b3d-3f0d-4a30-b24f-119ee8a7ad35)

This is one of the possible fixes
![image](https://github.com/daostack/common-backend/assets/9046616/3913a846-6d4d-462f-a499-0f0aa599e531)

2023-05-16 21:27 UTC, danielr18 commented
I also noticed a few absolute imports. We mostly use relative imports so we may want to always use relative, but it's ok with me if you want to mix both.

2023-05-18 10:59 UTC, ariel-dao commented on functions/src/chat/services/createChatChannel.ts
> +    })
Yes

2023-05-18 17:12 UTC, ariel-dao commented on functions/src/users/services/followFeedItem.ts
> +            }
removed

2023-05-18 17:36 UTC, danielr18 approved these changes

2023-05-18 17:36 UTC, danielr18 commented on functions/src/users/db/inbox/add.ts
> +    if (!existingInboxItem.empty) return;
We return the existing follow in the follow's add method. Should we do the same here?

2023-05-19 13:20 UTC, ariel-dao commented on functions/src/users/db/inbox/add.ts
> +    if (!existingInboxItem.empty) return;
I'll change it to return existing, but honestly I don't really like having the db functions doing any of that logic

2023-05-19 13:21 UTC, merged