Add immediate resolution proposals and support absolute approval/reject values
daostack/common-backend pull request #1884
Opened 2023-06-05 10:55 UTC by danielr18

Closes #1844

2023-06-09 14:51 UTC, ariel-dao commented on functions/src/proposals/business/proposals/calculateFinalState.ts
> +        if (maxRejectUnit === 'percent') {
percent as enum in all PR

2023-06-09 14:51 UTC, ariel-dao commented on functions/src/proposals/business/proposals/calculateFinalState.ts
> +        } else if (maxRejectUnit === 'absolute') {
enum

2023-06-09 15:06 UTC, ariel-dao requested changes
Looks ok, formatting makes it really tough to see changes, we'll format the entire project after this PR is merged.

This PR is quite dangerous even though it seems ok, please import production db locally and run the migrations to make sure the data looks valid.

Also, did you manage to test the flows with the new settings locally? It's pretty important and I don't think this one should be done on dev as it would be easy to miss some critical potential errors there

2023-06-09 15:10 UTC, ariel-dao commented on functions/src/proposals/services/proposals/createAssignCircle.ts
> +            resolutionType: ProposalResolutionType.WAIT_FOR_EXPIRATION,
Need to update related endpoints on Postman

2023-06-09 22:23 UTC, danielr18 commented on functions/src/proposals/business/proposals/calculateFinalState.ts
> +        if (maxRejectUnit === 'percent') {
Done

2023-06-09 22:23 UTC, danielr18 commented on functions/src/proposals/business/proposals/calculateFinalState.ts
> +        } else if (maxRejectUnit === 'absolute') {
Done

2023-06-10 00:16 UTC, danielr18 commented on functions/src/proposals/services/proposals/createAssignCircle.ts
> +            resolutionType: ProposalResolutionType.WAIT_FOR_EXPIRATION,
How should I update those?

2023-06-10 00:17 UTC, danielr18 commented
I've documented the process of importing the production DB.
The migration worked as expected.

2023-06-10 12:35 UTC, ariel-dao commented on functions/src/proposals/services/proposals/createAssignCircle.ts
> +            resolutionType: ProposalResolutionType.WAIT_FOR_EXPIRATION,
Go into our postman collection (you are already a part of it and change related endpoint payloads if needed - proposals probably only)

2023-06-10 12:35 UTC, merged

2023-06-10 12:36 UTC, ariel-dao commented
deployed to dev