Cb-1847 decrement count deleted messages
daostack/common-backend pull request #1899
Opened 2023-06-11 15:38 UTC by danielr18

2023-06-11 15:43 UTC, danielr18 commented
Need to create migration

2023-06-11 16:24 UTC, ariel-dao commented on functions/src/commons/business/decrementFeedObjectCountForUsersOnDelete.ts
> +                count: feedObjectUserUnique.count - 1,
make sure that count can't go below 0 (shouldn't happen but we can never know for sure)

2023-06-11 16:24 UTC, ariel-dao commented on functions/src/commons/business/decrementFeedObjectCountForUsersOnDelete.ts
> +                  count: feedItemFollow.count - 1,
count min 0

2023-06-11 16:24 UTC, ariel-dao commented on functions/src/commons/db/CommonFeedObjectUserUnique/add.ts
> +        .where("feedObjectId", "==", commonFeedObjectUserUnique.feedObjectId)
might need to index this

2023-06-11 16:25 UTC, ariel-dao requested changes
Looks good merge affter changes

2023-06-15 00:28 UTC, danielr18 commented on functions/src/commons/db/CommonFeedObjectUserUnique/add.ts
> +        .where("feedObjectId", "==", commonFeedObjectUserUnique.feedObjectId)
It already exists

2023-06-15 00:29 UTC, merged