System messages for new feed items in the space #1950
daostack/common-backend pull request #2024
Opened 2023-08-07 17:48 UTC by ariel-dao

Added system message definition that's executed on new feed item creation.
Common member added and other stuff that don't create feed items should be covered.
There are a few checks before creating: Titles and circle visibility.

2023-08-07 17:48 UTC, ariel-dao commented
@danielr18 @andreymikhadyuk Is there a known way to send text as a link in rich text?

2023-08-07 17:56 UTC, danielr18 requested changes

2023-08-07 17:56 UTC, danielr18 commented on functions/src/commons/business/createSystemMessagesOnFeedItemCreated.ts
> +export const createSystemMessagesOnFeedItemCreated = async (
Where will this function be called?

2023-08-07 18:28 UTC, ariel-dao commented on functions/src/commons/business/createSystemMessagesOnFeedItemCreated.ts
> +export const createSystemMessagesOnFeedItemCreated = async (
Missed a commit, fixed

2023-08-07 19:20 UTC, elatif2020 commented
> @danielr18 @andreymikhadyuk Is there a known way to send text as a link in rich text?

@ariel-dao 
we do it for the system messages about new space created

2023-08-08 04:40 UTC, andreymikhadyuk commented
@elatif2020 @ariel-dao @danielr18 we [construct](https://github.com/daostack/common-web/blob/dev/src/shared/components/Chat/ChatMessage/utils/getTextFromSystemMessage.tsx#L130) system messages on the FE side based on the type and data from BE.
There are also last messages which use just text from BE, but they are not clickable, so that info may contain just plain text.

2023-08-08 10:04 UTC, danielr18 approved these changes

2023-08-08 10:04 UTC, merged