Add hasPublicItems property to commons #2049
daostack/common-backend pull request #2055
Opened 2023-08-25 13:35 UTC by ariel-dao

Add tracker for common on public feed items based on filtering out pinned finned items and having an empty circle visibility - runs on update/delete and custom logic for add feed item

And a migration

2023-08-31 10:04 UTC, danielr18 requested changes

2023-08-31 10:04 UTC, danielr18 commented on functions/src/commons/business/checkForPublicItems.ts
> +  ).empty;
Will this require an index?

2023-08-31 10:04 UTC, danielr18 commented on functions/src/commons/controllers/getFeedItems.ts
>          userId: req.user.uid,
Should it become `req.user?.uid`?

2023-09-04 15:59 UTC, ariel-dao commented on functions/src/commons/business/checkForPublicItems.ts
> +  ).empty;
added

2023-09-08 09:56 UTC, ariel-dao commented
@danielr18 @elatif2020 pinned items (general discussions) are filtered when checking for public items, should I change it?

aside from that, can I merge this?

2023-09-10 10:42 UTC, elatif2020 commented
> @danielr18 @elatif2020 pinned items (general discussions) are filtered when checking for public items, should I change it?
> 
> aside from that, can I merge this?

Why are we filtering out pinned items? @ariel-dao @andreymikhadyuk

2023-09-11 11:15 UTC, ariel-dao commented
- [x] Remove filtering by pinned/general

2023-09-14 10:30 UTC, danielr18 approved these changes

2023-09-14 10:30 UTC, merged