CM-265: Create Common - Tagline and About fields should be not required
daostack/common-backend pull request #317
Opened 2021-04-05 09:43 UTC by baticpro

2021-04-05 13:48 UTC, lpetkov-sw requested changes
@baticpro you need to update the tests as well, as they have logic for the fields to be required.

2021-04-06 06:05 UTC, alexander2001i requested changes
The types should also be changed to reflect that change. It would not be cool the type to say that the value is cannot be null and then it is null

2021-04-07 13:46 UTC, alexander2001i commented
@baticpro Any progress?

2021-04-09 08:38 UTC, alexander2001i approved these changes

2021-04-09 08:38 UTC, merged