CM-266 - common creation min contribution
daostack/common-backend pull request #318
Opened 2021-04-05 11:19 UTC by watchtower314

Issue #266 

THIS HAS A FRONTEND PR TOO!
Tests are failing -> fixing them [wip]

2021-04-06 06:03 UTC, alexander2001i reviewed
I'm not getting what this PR is trying to modify. Can you elaborate?

2021-04-06 07:03 UTC, watchtower314 commented
@alexander2001i yeah, took me a few reads of the ticket to understand to motivation here 😅
so basically, when creating a common, it is required that there will be a minFeeToJoin (which must be at least $5). That means that users cannot join for free, so there's a new ui change that allows the common creator to decide if users can join for free
<img width="555" alt="Screen Shot 2021-04-06 at 3 01 40" src="https://user-images.githubusercontent.com/30501647/113671509-72c08080-9684-11eb-990b-1c30cf2a8d15.png">
When the creator ticks the checkbox, we need to allow users to join without providing the minimum contribution.

If you have more questions/suggestions, let me know ☺️

Ticket: https://github.com/daostack/common-monorepo/issues/266

2021-04-06 07:48 UTC, alexander2001i commented
@watchtower314 No, I don't. Thanks for the explanation

2021-04-06 07:52 UTC, alexander2001i requested changes

2021-04-06 07:52 UTC, alexander2001i commented on packages/firebase/functions/src/common/business/createCommon.ts
> +  zeroContribution: yup.boolean().required(),
Maybe don't make it required, but rater if not provided set to `false`?

2021-04-06 07:52 UTC, alexander2001i commented on packages/firebase/functions/src/proposals/business/createJoinRequest.ts
> +  if (common.metadata.minFeeToJoin > payload.funding && !common.metadata.zeroContribution) {
This is not correct, because if zero dollar contributions are allowed it will allow the user to create contribution, lower than the minimum

2021-04-07 14:09 UTC, watchtower314 commented on packages/firebase/functions/src/proposals/business/createJoinRequest.ts
> +  if (common.metadata.minFeeToJoin > payload.funding && !common.metadata.zeroContribution) {
You're right! I'll fix it, Thank you! :)

2021-04-07 14:42 UTC, lpetkov-sw reviewed
Hey @watchtower314 as it's described in the ticket you have removed the Safety Period feature, but here I don't see any logic for that. I think at least you have to check the tests and the validation for the common creation and exclude/remove any logic about that field.

2021-04-08 05:07 UTC, alexander2001i commented on packages/firebase/functions/src/proposals/business/createJoinRequest.ts
> +  if (common.metadata.minFeeToJoin > payload.funding && !common.metadata.zeroContribution) {
You are welcome 😄

2021-04-08 09:09 UTC, watchtower314 commented
> Hey @watchtower314 as it's described in the ticket you have removed the Safety Period feature, but here I don't see any logic for that. I think at least you have to check the tests and the validation for the common creation and exclude/remove any logic about that field.

So I haven't removed the safety period, just forced it to be `today`, and we are still sending it from the frontend, should I remove it altogether?

2021-04-08 11:48 UTC, lpetkov-sw commented on packages/firebase/__tests__/funtions/proposal.test.ts
> +  description: 'I wanna be a part, but pay less that $5',
Typo here: that -> than But no important at all :D

2021-04-08 11:57 UTC, lpetkov-sw commented
> > Hey @watchtower314 as it's described in the ticket you have removed the Safety Period feature, but here I don't see any logic for that. I think at least you have to check the tests and the validation for the common creation and exclude/remove any logic about that field.
> 
> So I haven't removed the safety period, just forced it to be `today`, and we are still sending it from the frontend, should I remove it altogether?

@alexander2001i What's your opinion ?

2021-04-08 11:59 UTC, alexander2001i commented
Yes, It thing it will be the best to not have it at all rather than having a dummy value

2021-04-09 05:08 UTC, alexander2001i approved these changes

2021-04-09 05:09 UTC, merged