notification for posts and member added
daostack/common-backend pull request #55
Opened 2021-02-09 16:41 UTC by watchtower314

I had to fix multiple eslint issues (the same ones I already fixed in firebase/CM-1513-permissions-for-users)

2021-02-09 16:45 UTC, watchtower314 commented on packages/firebase/functions/src/notification/notification.ts
> +  [EVENT_TYPES.DISCUSSION_CREATED]: {
This was merged before, not sure what happened

2021-02-09 18:24 UTC, alexander2001i reviewed
I'm sleepy so I looked it. Will do real review tomorrow 🤣￼

2021-02-09 18:24 UTC, alexander2001i commented on packages/firebase/functions/src/event/event.ts
> + * [handleUserFilter description]
cool

2021-02-10 09:54 UTC, watchtower314 commented on packages/firebase/functions/src/event/event.ts
> +const handleUserFilter = (userIDs: string[], userFilter: string[]): boolean => {
This function was moved here because eslint showed an error that it was used before it was defined

2021-02-10 09:54 UTC, watchtower314 commented on packages/firebase/functions/src/event/event.ts
> +const excludeOwner = (membersId: string[], ownerId: string): string[] => (
This function was moved here because eslint showed an error that it was used before it was defined

2021-02-10 09:56 UTC, watchtower314 commented on packages/firebase/functions/src/event/index.ts
> -export interface IEventModel {
Moved this to @common/types because esilnt here doesn't allow interface to start with an `I` 🤷🏽‍♀️

2021-02-10 09:56 UTC, watchtower314 commented on packages/firebase/functions/src/notification/notification.ts
> +/*global logger*/
eslint asks to define globals like this

2021-02-10 09:57 UTC, watchtower314 commented on packages/firebase/functions/src/notification/notification.ts
> -export interface INotification {
Moved this to @common/types because esilnt here doesn't allow interface to start with an `I` 🤷🏽‍♀️

2021-02-10 09:57 UTC, watchtower314 commented on packages/firebase/functions/src/notification/notification.ts
> -interface IEventData {
Moved this to @common/types because esilnt here doesn't allow interface to start with an `I` 🤷🏽‍♀️

2021-02-11 13:03 UTC, alexander2001i commented on packages/firebase/functions/src/notification/notification.ts
> +  [EVENT_TYPES.DISCUSSION_CREATED]: {
Git magic :D

2021-02-11 13:04 UTC, alexander2001i requested changes
I don't think this PR should contain permissions stuff

2021-02-11 13:04 UTC, alexander2001i commented on packages/types/src/entities/IPermission.ts
> +export type Role = 'founder'| 'moderator' | 'other';
Not sure that this should be part of this PR?

2021-02-11 13:04 UTC, alexander2001i commented on packages/types/src/entities/IUserEntity.ts
> +}
I smell conflict cause I did the same thing :D

2021-02-11 13:06 UTC, watchtower314 commented on packages/types/src/entities/IPermission.ts
> +export type Role = 'founder'| 'moderator' | 'other';
Its not, I just got tons of eslint error (26) so I added it here as well, should I revert it and only have the notification part?

2021-02-11 13:06 UTC, watchtower314 commented on packages/types/src/entities/IUserEntity.ts
> +}
😂

2021-02-15 14:07 UTC, alexander2001i approved these changes

2021-02-15 14:08 UTC, merged