Consolidated new GraphQL API
daostack/common-backend pull request #793
Opened 2021-09-09 08:35 UTC by SobolevYuri

2021-09-09 13:42 UTC, MeyerPV requested changes

2021-09-09 13:42 UTC, MeyerPV commented on packages/core/prisma/migrations/20210823214132_discussions_report_flag/migration.sql
> +ALTER TABLE "Discussion" ADD COLUMN     "flag" "ReportFlag" NOT NULL DEFAULT E'Clear';
DEFAULT **!!!E!!!**'Clear';
Should it be here? `E`

2021-09-09 19:41 UTC, SobolevYuri commented on packages/core/prisma/migrations/20210823214132_discussions_report_flag/migration.sql
> +ALTER TABLE "Discussion" ADD COLUMN     "flag" "ReportFlag" NOT NULL DEFAULT E'Clear';
i didn't find any answers for this (was trying to find any mentions about possible flags for 'DEFAULT') so i've just removed this sign from there (and then rechecked). Actually this 'E'-sign was placed there during auto-generating of the postgres migration (by a special yarn command), but the reason of adding this sign (by the system) is still unclear :-D

2021-09-10 08:37 UTC, MeyerPV approved these changes

2021-09-30 08:45 UTC, watchtower314 approved these changes

2021-10-04 11:15 UTC, merged