Moderation batch 2
daostack/common-backend pull request #82
Opened 2021-02-16 09:00 UTC by watchtower314

- [x] Add missing typing
- [x] Add validation

2021-02-19 06:31 UTC, alexander2001i commented on packages/firebase/functions/src/core/domain/users/business/hasPermission.ts
> +  user?.roles.forEach((role) => {
Why do you have `?` here?

2021-02-19 06:31 UTC, alexander2001i commented on packages/firebase/functions/src/discussion/database/moderateDiscussion.ts
> +export const moderateDiscussion = async (discussionId: string, moderationEntity) => {
I do not agree with this (of course you do you and feel free to ignore). If you need to update the discussion there should only be update discussion database method and implementation details like updating the moderation should be handled from the business layer

2021-02-19 06:31 UTC, alexander2001i commented on packages/firebase/functions/src/discussionMessage/database/moderateDiscussionMessage.ts
> +export const moderateDiscussionMessage = async (discussionMessageId: string, moderationEntity) => {
The same thing as above.

2021-02-19 06:31 UTC, alexander2001i commented on packages/firebase/functions/src/moderation/business/hideContent.ts
> +    throw new CommonError(`Permission denied`);
Maybe different error. Throwing this will return `500` and the appropriate HTTP code is s `403`. I think there is `UnathorizedError` already there

2021-02-19 06:31 UTC, alexander2001i commented on packages/firebase/functions/src/moderation/business/hideContent.ts
> +  const { moderation, commonId, userId, type } = payload;
I do not see any kind of validation (nor types)

2021-02-19 06:31 UTC, alexander2001i commented on packages/firebase/functions/src/moderation/business/hideContent.ts
> +    reasons: moderation.reasons?.split(',') || [], //IReasons
You know it is `IReasons` but the compilator does not 😄

2021-02-19 06:31 UTC, alexander2001i commented on packages/firebase/functions/src/moderation/business/updateEntity.ts
> +export const updateEntity = async (itemId: string, moderationEntity, type: string) => {
The name is not ok. User, common, proposal, all of these are also entities

2021-02-19 06:31 UTC, alexander2001i commented on packages/firebase/functions/src/moderation/business/updateEntity.ts
> +      // code...
😄

2021-02-19 06:31 UTC, alexander2001i commented on packages/firebase/functions/src/moderation/index.ts
> +        userId: req.user.uid
👍

2021-02-19 06:31 UTC, alexander2001i commented on packages/firebase/functions/src/proposals/database/moderateProposal.ts
> +}
Same as above, wayyy up 😄

2021-02-25 07:48 UTC, alexander2001i requested changes

2021-02-25 07:48 UTC, alexander2001i commented on packages/firebase/functions/src/core/domain/users/business/hasPermission.ts
> + * @return boolean  - true -> user has permission, otherwise -> false
```suggestion
 * @return boolean  - indicating whether the user has permission or not
```

2021-02-25 07:48 UTC, alexander2001i commented on packages/firebase/functions/src/discussion/database/getDiscussion.ts
> +import { IDiscussionEntity } from '@common/types';
👍

2021-02-25 07:48 UTC, alexander2001i commented on packages/firebase/functions/src/event/event.ts
> +      return [common.members[0].userId]; // send to founder for now, need to send to all moderators
Not like this. There is no guarantee that the members will be always like this (they should be, but you never know and there are no protections in place), so maybe: 

```suggestion
      return [common.metadata.founderId]; // send to founder for now, need to send to all moderators
```

What do you think?

2021-02-25 07:48 UTC, alexander2001i commented on packages/firebase/functions/src/moderation/business/hideContent.ts
> +    } as IModerationEntity,
I'm not a fan of this. Entity means one document, not part of other

2021-02-25 07:48 UTC, alexander2001i commented on packages/firebase/functions/src/moderation/business/reportContent.ts
> +    throw new CommonError('Only members can report');
Looks like `AuthorizationError` to me. We what to get HTTP 403, not HTTP 500

2021-02-25 07:48 UTC, alexander2001i commented on packages/firebase/functions/src/moderation/business/showContent.ts
> +import { firestore } from 'firebase-admin';
Either with or without spaces. Pick one 😄

2021-02-25 07:48 UTC, alexander2001i commented on packages/firebase/functions/src/moderation/business/showContent.ts
> +    throw new UnauthorizedError();
Ahhaa, you use it here 👍

2021-02-25 07:48 UTC, alexander2001i commented on packages/firebase/functions/src/moderation/business/updateEntity.ts
> + * @return {Promise<any>}        [description]
Those comments are not in line with the other ones

2021-02-25 07:48 UTC, alexander2001i commented on packages/types/src/entities/IModerationEntity.ts
> +    reasons: string[];
I see it like this:

<img width="416" alt="image" src="https://user-images.githubusercontent.com/45437412/109120414-940d8300-774e-11eb-9c5c-2f9c61a84d5e.png">

Not sure if it is the same for you

2021-02-25 07:48 UTC, alexander2001i commented on packages/types/src/entities/IProposalEntity.ts
> +  moderation?: IModerationEntity;
👎

2021-02-25 09:03 UTC, watchtower314 commented on packages/firebase/functions/src/event/event.ts
> +      return [common.members[0].userId]; // send to founder for now, need to send to all moderators
Yes, I agree :)

2021-02-25 09:04 UTC, watchtower314 commented on packages/firebase/functions/src/moderation/business/hideContent.ts
> +    } as IModerationEntity,
So do we event need to call moderation an `entity` if it's not an entity of its own, and only a part of other entities?

2021-02-25 09:11 UTC, watchtower314 commented on packages/types/src/entities/IModerationEntity.ts
> +    reasons: string[];
🤷🏽‍♀️
<img width="262" alt="Screen Shot 2021-02-25 at 4 10 36" src="https://user-images.githubusercontent.com/30501647/109130208-72e16e00-771f-11eb-9f28-40d1c15282c9.png">

2021-02-25 09:12 UTC, watchtower314 commented on packages/types/src/entities/IModerationEntity.ts
> +    reasons: string[];
ooh but I was using tabs, fixing it

2021-03-01 12:30 UTC, alexander2001i approved these changes

2021-03-01 12:49 UTC, merged