CM-1502 - validation for edit common
daostack/common-backend pull request #9
Opened 2021-02-01 12:38 UTC by watchtower314

2021-02-02 07:04 UTC, alexander2001i requested changes

2021-02-02 07:04 UTC, alexander2001i commented on packages/firebase/functions/src/common/business/updateCommon.ts
> +  // TODO check if user has permission to edit this common when permissions pr is merged
Don't forget ☝️

2021-02-02 07:04 UTC, alexander2001i commented on packages/firebase/functions/src/common/index.ts
> +        userId: req.user.uid
✨

2021-02-02 07:04 UTC, alexander2001i commented on packages/firebase/functions/src/common/types.ts
> +      founderId: string;
Can you remove the founder ID from here please. It should not be mutable

2021-02-02 07:04 UTC, alexander2001i commented on packages/firebase/functions/src/commonEditHistory/business/createCommonHistory.ts
> +  commonEditHistoryDb.add(originalCommon.id, commonHistoryRecord); // adding history
What I meant here is that we should not pass the ID on creation. In a normal database (Postgres for example) the ID is generated for us, so it will be good practice to generate it in the database method `database/addCommonHistory`. Also if we leave it like that the ID will be the same as the original common meaning that we are forcing `0 or 1 to 1 relationship` and I think one common may have more than one history change?

2021-02-02 16:21 UTC, watchtower314 commented on packages/firebase/functions/src/commonEditHistory/business/createCommonHistory.ts
> +  commonEditHistoryDb.add(originalCommon.id, commonHistoryRecord); // adding history
Oh, so you're saying that this way we can have multiple histories for the same common, with the same id, right?
If so, then yeah, that's not what we want, fixing it :)

2021-02-03 09:13 UTC, watchtower314 commented on packages/firebase/functions/src/common/business/updateCommon.ts
> +  // TODO check if user has permission to edit this common when permissions pr is merged
Permissions is still not merged, also, I think I'm going to move the pr from `common-firebase` to here

2021-02-04 06:59 UTC, alexander2001i approved these changes

2021-02-04 06:59 UTC, merged