CM - payme redirect
daostack/common-backend pull request #953
Opened 2021-12-23 12:02 UTC by watchtower314

2021-12-23 13:04 UTC, MeyerPVKernelics requested changes

2021-12-23 13:04 UTC, MeyerPVKernelics commented on functions/src/payments/providers/payme/payIn/chargeBuyerToken.ts
> +                sale_return_url: 'https://google.com'
maybe redirect to app.common.io

2021-12-23 13:52 UTC, MeyerPVKernelics approved these changes

2021-12-23 14:49 UTC, ariel-dao commented on functions/src/shared/schemas/billingDetailsValidationSchema.ts
> +    ID: yup.string().when("country", {
change ID to socialId

2021-12-23 14:50 UTC, ariel-dao commented on functions/src/proposals/business/createJoinRequest.ts
> +  if (payload.cardId !== payload.proposerId) {
Delete , cardId is unique not userId

2021-12-23 14:50 UTC, ariel-dao commented on functions/src/payments/providers/payme/payIn/createBuyerTokenPage.ts
> +                sale_return_url: 'https://common.io'
delete sale return URL we will put loader URL when we get

2021-12-23 14:50 UTC, ariel-dao requested changes
Left comments

2021-12-28 09:57 UTC, ariel-dao commented
waiting for loader URL before merging this

2021-12-28 20:04 UTC, ariel-dao commented on functions/src/payments/providers/payme/payIn/chargeBuyerToken.ts
> +                sale_return_url: 'https://google.com'
redirect here will only affect the webview/iframe not the main window

2021-12-29 16:46 UTC, watchtower314 commented on functions/src/payments/providers/payme/payIn/createBuyerTokenPage.ts
> +                sale_return_url: 'https://storage.googleapis.com/common-daostack.appspot.com/public_img/loader.jpeg'
@ariel-dao this is the url from Alex

2021-12-29 16:58 UTC, ariel-dao approved these changes

2021-12-29 16:58 UTC, merged